---
title: "Shiny Demo"
format: html
server: shiny
---

## Shiny Presentation

This R Markdown presentation is made interactive using Shiny. The viewers of the presentation can change the assumptions underlying what's presented and see the results immediately. 

To learn more, see [Interactive Documents](https://quarto.org/docs/interactive/shiny/).

## Interactive Plot

```{r}
library(tidyverse)
```

```{r}

inputPanel(
  sliderInput("n_sample", label = "Number of samples:",
              min = 2, max = 1000, step = 1, value = 20),
  sliderInput("correlation", label = "Correlation:",
              min = -1, max = 1, step = .01, value = 0),
  actionButton("button", label = "Regenerate Sample")
)
plotOutput("distPlot")
```

```{r}
#| context: server

output$distPlot <- renderPlot({
  library(tidyverse)
  input$button
  
  x <- rnorm(input$n_sample, 0, 1)
  y <- input$correlation*x + rnorm(input$n_sample, 0, 1-input$correlation^2)
  
  data <- tibble(x = x, y = y)
  
  model <- lm(y~x)
  
  ggplot(data, aes(x = x, y = y)) +
    geom_point() +
    lims(x = c(-3, 3), y = c(-3, 3)) +
    coord_fixed(ratio = 1) +
    geom_abline(aes(intercept = 0, slope = input$correlation, color = "True")) +
    geom_abline(aes(intercept = model$coefficients[1], slope = model$coefficients[2], color = "Fitted")) +
    scale_color_manual(name="Regression Line",
                     breaks=c("True", "Fitted"),
                     values=c("True"="red", "Fitted"="black"))
})
```