---
title: "Assignment 1"
subtitle: "STA3100"
format:
  pdf:
    pdf-engine: lualatex
    pdf-standard: ua-2
lang: en
geometry:
  - margin = 1in
execute:
  eval: false
  echo: true
---

## Reading Assignment:

-   [rp4ds](https://bookdown.org/rdpeng/rprogdatascience/): 2, 4.1-15, 9.1, 10
-   [r4ds](https://r4ds.had.co.nz/): 1, 20.1-4
-   (Optional) [advr](https://adv-r.hadley.nz/): 1, 3.1-3.3.2, 4.2.1

## Problems:

Please use Quarto for this HW and all future HWs.

1.  Calculate the remainder after dividing 31079 into 170166719.

2.  Using one line of R code, calculate the respective areas of circles having radii 3, 4, ..., 100.

3.  Using one line of R code, calculate the interest earned on an investment of \$2000, assuming an interest rate of 3% compounded annually, for terms of 1, 2, ..., 30 years.

4.  Using the `rep()` and `seq()` functions as needed, create the following vectors:\
    $\{\ 0 \ \ 0 \ \ 0 \ \ 0 \ \ 0 \ \ 1 \ \ 1 \ \ 1 \ \ 1 \ \ 1 \ \ 2 \ \ 2 \ \ 2 \ \ 2 \ \ 2 \ \ 3 \ \ 3 \ \ 3 \ \ 3 \ \ 3 \ \ 4 \ \ 4 \ \ 4 \ \ 4 \ \ 4\ \}$\
    $\{\ 1 \ \ 2 \ \ 3 \ \ 4 \ \ 5 \ \ 1 \ \ 2 \ \ 3 \ \ 4 \ \ 5 \ \ 1 \ \ 2 \ \ 3 \ \ 4 \ \ 5 \ \ 1 \ \ 2 \ \ 3 \ \ 4 \ \ 5 \ \ 1 \ \ 2 \ \ 3 \ \ 4 \ \ 5\ \}$\
    $\{\ 1 \ \ 2 \ \ 3 \ \ 4 \ \ 5 \ \ 2 \ \ 3 \ \ 4 \ \ 5 \ \ 6 \ \ 3 \ \ 4 \ \ 5 \ \ 6 \ \ 7 \ \ 4 \ \ 5 \ \ 6 \ \ 7 \ \ 8 \ \ 5 \ \ 6 \ \ 7 \ \ 8 \ \ 9\ \}$

5.  Find the value of $\sum_{j=1}^{n}r^j$, for all values of *n* between 1 and 100, when r = 1.08. (Hint: `cumsum()`)

6.  Use R to identify the elements of the sequence {2^1^, 2^2^, ..., 2^15^} that exceed the corresponding elements of the sequence {1^3^, 2^3^, ..., 15^3^}.

7.  The following are a sample of observations on incoming solar radiation at a greenhouse:\
    $\{\ 11.1 \ \ 10.6 \ \ 6.3 \ \ 8.8 \ \ 10.7 \ \ 11.2 \ \ 8.9 \ \ 12.2\ \}$

    a)  Assign the data to an object called **solar.radiation**.
    b)  Find the mean, median, range, and variance of the radiation observations.
    c)  Add 10 to each observation of **solar.radiation** and assign the result to **sr10**. Find the mean, median, range, and variance of **sr10**. Which statistics change, and by how much?
    d)  Multiply each observation of **solar.radiation** by -2 and assign the result to **srm2**. Find the mean, median, range and variance of **srm2**. How do the statistics change now?
